# Generated by Django 4.0.4 on 2022-06-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('number', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=255)),
                ('answer_group', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.test')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('mobile_phone', models.CharField(blank=True, max_length=255)),
                ('birth', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('subdivision', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.organization')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.test')),
            ],
            options={
                'db_table': 'methodology',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('attention', models.BooleanField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.profile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.test')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=255)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.interview')),
            ],
            options={
                'db_table': 'choices',
            },
        ),
    ]
